### ISSUE TITLE
Missing Stats for large Catalog

### ISSUE THREAD

**Issue by chrisLovesCode** [lukashlavacka/ReactJS-LightroomCatalog-Viewer#1]
Hey Lukas,
i've experienced problems with an large catalog (~ 500mb). no recommendations and no charts :(
seems the app runs out of memory, since console prints:
`worker.sql.js:482 Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at Ra (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:32:124)
    at Qa (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:32:22)
    at p (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:482:103)
    at Function.ba [as Gb] (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:12:164)
    at Ia (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:391:297)
    at JR (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:461:142577)
    at MR (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:461:154016)
    at Vu (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:462:15175)
    at cg (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:454:93578)
    at rJ (http://lukashlavacka.github.io/ReactJS-LightroomCatalog-Viewer/lib/worker.sql.js:463:132417)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.`

**Comment by chrisLovesCode** [comment]
PS: i've you don't own a catalog with ~500mb i would be happy to help to upload my catalog for you, let me know
